import Link from "next/link";
import type { Metadata } from "next";
export const metadata: Metadata = { title: "Privacidade na demonstração" };
export default function Page() { return <div className="mx-auto max-w-3xl space-y-6 px-4 py-12 text-slate-700 sm:px-6">
<section><h1 className="mb-3 text-3xl font-bold text-slate-900">Privacidade na demonstração</h1><p className="leading-relaxed">Utilize dados fictícios ao testar esta versão. Não introduza documentos pessoais ou dados de pagamento reais.</p></section>
<section><h2 className="mb-3 text-xl font-bold text-slate-900">Dados guardados no navegador</h2><p className="leading-relaxed">A conta de demonstração é guardada no armazenamento local do navegador até terminar a sessão ou limpar os dados do site. A viagem e os dados de passageiros introduzidos são guardados no armazenamento da sessão para permitir continuar após atualizar a página. Pode eliminá-los limpando os dados do site no navegador.</p></section>
<section><h2 className="mb-3 text-xl font-bold text-slate-900">Serviços externos</h2><p className="leading-relaxed">As fotografias de destinos podem ser carregadas de um fornecedor externo de imagens. Existe também uma funcionalidade de consulta de BI: ao ser usada, o número introduzido é enviado pelo servidor ao serviço do SME para consultar o nome. Não use documentos reais para experimentar esta funcionalidade.</p></section>
<section><h2 className="mb-3 text-xl font-bold text-slate-900">Lançamento comercial</h2><p className="leading-relaxed">Antes de recolher dados para reservas reais, será necessário publicar a identificação e o contacto da entidade responsável, os fornecedores envolvidos, as finalidades, os prazos de conservação e os meios de exercício dos direitos aplicáveis. Esta informação de demonstração não substitui essa política operacional.</p></section>
<p className="text-sm">Última revisão: 7 de outubro de 2026.</p><Link href="/#perguntas" className="inline-flex min-h-11 items-center font-semibold text-[var(--action)]">Consultar perguntas frequentes →</Link></div>; }
